force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <description>This object is used to hold all recruiters details.</description>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Managers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <description>Please provide your Contact Number</description>
    <label>Contact Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <description>Email ID</description>
    <inlineHelpText>Provide a valid Email ID</inlineHelpText>
    <label>Email ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Belagavi</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This objecct is used to hold all the open positions in the Org.</description>
    <label>Position</label>
    <nameField>
        <label>New Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>Hiring_Manager__c</referenceTo>
    <relationshipLabel>My Positions</relationshipLabel>
    <relationshipName>My_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/HR_Email__c.field-meta.xml
<CustomField>
    <fullName>HR_Email__c</fullName>
    <label>HR Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Panaji</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Multiple Cities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Max_Pay__c.field-meta.xml
<CustomField>
    <fullName>Max_Pay__c</fullName>
    <label>Max. Budget</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <label>Number of Positions</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Passport_Required_del__c.field-meta.xml
<CustomField>
    <fullName>Passport_Required_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passport Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Description__c.field-meta.xml
<CustomField>
    <fullName>Position_Description__c</fullName>
    <label>Position Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Open - Approved</fullName>
            </value>
            <value>
                <fullName>In - Progress</fullName>
            </value>
            <value>
                <fullName>Recruited</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Skills_Required__c.field-meta.xml
<CustomField>
    <fullName>Skills_Required__c</fullName>
    <label>Skills Required</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/CommonUtility.cls
public class CommonUtility {
	
    String hm_id;
    
    public void insertHiringManagerRecord()
    {
        //Creating hiring manager object
        Hiring_Manager__c hm=new Hiring_Manager__c();
        
        //Assigining the values
        hm.Name = 'Ashwini Gawade';
        hm.Contact_Number__c='8923231293';
        hm.Email_ID__c='ss1510@gmail.com';
        hm.Location__c ='Belagavi';
        
        insert hm;

		if(hm.id!= null)
        {
            system.debug('The Hiring Manager record has been successfully inserted. Record ID is.... '+hm.id);
        }
        hm_id=hm.Id;
     }
    
    public void createNewPositionRecord()
    {
        //creating a object 
        Position__c pos = new Position__c();
        
        //Assigning the values
        pos.name ='TrackWise Digital Admin';
        pos.Close_Date__c= system.today().Adddays(26);
        pos.Open_Date__c= system.today();
        pos.HR_Email__c= 'kish@gmail.com';
        pos.Location__c='Kochi';
        pos.Number_of_Positions__c=14;
        pos.Passport_Required_del__c=true;
        pos.Position_Description__c='This position will be dynamic and challenging and we are looking for the right individual that can think on their feet and really embrace new challenges as they come along.';
        pos.Skills_Required__c='Work closely with Site NC lead for management for NC / CAPA process for SGTC & R&D test lab.';
    	pos.Position_Status__c='Opened';
        pos.Max_Pay__c=1200000;
        pos.RecordTypeId=schema.sobjecttype.position__c.getrecordtypeinfosbyname().get('IT Position Record Type').Getrecordtypeid();
        
        pos.Hiring_Manager__c=hm_id;
        
        insert pos;
        
        if(pos.id!=null)
        {
            system.debug('The position record has been successfully inserted. Record ID is....'+pos.Id);
        }
        
    }
    
    public void GetStringlength(String str)
    {
        system.debug('The length of the String is : '+str.length());
    }
    
}