force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <customHelpPage>Calculator</customHelpPage>
    <description>Stores the data of the candidates for hiring</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Candidate_ID__c.field-meta.xml
<CustomField>
    <fullName>Candidate_ID__c</fullName>
    <description>It is a ID</description>
    <displayFormat>CID-{000000}</displayFormat>
    <label>Candidate ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_CTC__c.field-meta.xml
<CustomField>
    <fullName>Current_CTC__c</fullName>
    <label>Current CTC</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Expected_CTC__c.field-meta.xml
<CustomField>
    <fullName>Expected_CTC__c</fullName>
    <label>Expected CTC</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Belagavi</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <label>Class Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Class</relationshipLabel>
    <relationshipName>Class</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <description>This object is used to hold all recruiters details.</description>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Managers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <description>Please provide your Contact Number</description>
    <label>Contact Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <description>Email ID</description>
    <inlineHelpText>Provide a valid Email ID</inlineHelpText>
    <label>Email ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Belagavi</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ProductInterest__c.field-meta.xml
<CustomField>
    <fullName>ProductInterest__c</fullName>
    <label>Product Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>Scanner</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Tabs</fullName>
            </value>
            <value>
                <fullName>Projector</fullName>
            </value>
            <value>
                <fullName>DTH Service</fullName>
            </value>
            <value>
                <fullName>Internet Service</fullName>
            </value>
            <value>
                <fullName>Other Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This objecct is used to hold all the open positions in the Org.</description>
    <label>Position</label>
    <nameField>
        <label>New Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>Hiring_Manager__c</referenceTo>
    <relationshipLabel>My Positions</relationshipLabel>
    <relationshipName>My_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Panaji</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Multiple Cities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Passport_Required_del__c.field-meta.xml
<CustomField>
    <fullName>Passport_Required_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passport Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Open - Approved</fullName>
            </value>
            <value>
                <fullName>In - Progress</fullName>
            </value>
            <value>
                <fullName>Recruited</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommonHelper.cls
public class CommonHelper
{
    public void BulkinsertHiringManager(Integer noOfRcords)
    {
       List<Hiring_Manager__c> lstManagers= new List<Hiring_Manager__c>();  	//List for Hiring Manager
       
        if(noOfRcords > 0 && noOfRcords !=null)
        {
            for(integer i=1;i<=noOfRcords; i++)
            {
                Hiring_Manager__c hm=new Hiring_Manager__c();	//object hiring manager 
                
                hm.Name='Recruiter'+i;
                hm.Contact_Number__c='9876543'+i;
                hm.Email_ID__c='test'+i+'@gmail.com';  
                
                lstManagers.add(hm);
            }    
            
        }
        system.debug(lstManagers.size());
        
        if(! lstManagers.isEmpty())
        {
            insert lstManagers;
            for(Hiring_manager__c hm : lstManagers)
            {
                system.debug(hm);
            }
        }
    }
   
    public void getContactAndAssociatedParentDetails(string contactlastname)
    {
        string contacts = 'select id, firstname, lastname, email, phone, fax, account.name, account.industry, account.rating, account.active__c, account.owner.firstname, account.owner.lastname, account.owner.email from contact where lastname =: contactlastname';
    	List<Contact> lstcontacts = Database.query(contacts);
        
        if(! lstcontacts.isempty())
        {
            for(Contact temp : lstcontacts)
            {
                system.debug('The record details are : '+temp);
                system.debug('The Parent details are : '+ temp.Account);
                system.debug('The Parent details are : '+ temp.Account.owner);
            }
        }
        
        
    }
    
    public void getaccountRecordsUsingID()
    {
        List<Account> accRecords = [select id, name, industry from account where industry in ('Finance')];
        system.debug('The count of records is : '+ accrecords.size());
        for(Account temp : accrecords)
        {
        	system.debug(temp.id);
            system.debug(temp.name);
            system.debug(temp.Industry);
            system.debug('------------------------------------------------------');
        }
    }
    
    public void getCountPerIndustry()
    {
   		AggregateResult[] countAcc=[select industry, count(id) from account group by industry];
        
        if(! countAcc.isEmpty())
        {
            for(AggregateResult agg : countAcc)
            {
                system.debug(agg);
            }
            
        }
        
    }
    
    public void getCountofAccounts()
    {
    	// Static Method
    	integer accCount = [select count() from account];
        system.debug('The count of acc records is :' + accCount );
        
        //Dynamic Method
        string count = 'select count() from contact';
        integer temp = Database.countQuery(count);
        system.debug('The count of contacts is : '+temp);
        
    }
        
    public void getUnassociatedContacts()
    {
        string contactsQuery = 'Select id, firstname, lastname, email, phone, fax from contacts where accountid = null order by lastname asc';
        
        List<Contact> lstcontacts= Database.query(contactsQuery);
        
        system.debug('The collection size is : '+ lstcontacts.size());
        
        if(! lstcontacts.isempty())
        {
            for(Contact temp : lstcontacts)
            {
                system.debug('The record details are : '+ temp);
            }
        }
    }
    
    public void getcontactsbysearchtext(string searchtext)
    {
        if(searchtext != null && searchtext != '')
        {
            string contactsquery = 'select id, firstname, lastname, email, phone, fax from contact';
            
            if(Pattern.matches('[a-zA-Z0-9._-]+@[a-zA-Z]+.[a-zA-Z]{2,4}', searchtext))
            {
                system.debug('The search text is in email format...');
            }
            else
            {
                system.debug('The search text is in string format...');
            }
        }
        
        
    }
    
    public void getPositionRecordsDynamically(string city)
    {
        List<Position__c> lstpos=[select id, name, Location__c from Position__c where Location__c =: city];
        
        system.debug('The count seems to be : '+lstpos.size());
        
        if(! lstpos.isempty())
        {
            for(Position__c pos : lstpos)
            {
                system.debug('position record is : '+pos);
            }
        }
        
    }
    
    public void getAllClassRecords()
    {
        Map<id, Class__c> mapClass=new Map<id, Class__c>(); // defining the map
        
		List<Class__c> lstClass=[select ID,name,Teacher__c,CurrencyIsoCode from Class__c];//defining the list
        //copying class records to map
        if(! lstClass.isEmpty())
        {
            for(Class__c clas : lstclass)
            {
                Mapclass.put(clas.id, clas);
            }
        }
        
        
            }       
            
	public void getAllCandidateRecords()
	{
        map<id, Candidate__c> mapcandidates = new map<id, Candidate__c>();
        List<Candidate__c> lstcandidate=[select id, Name, Candidate_ID__c, Contact_Number__c, 
                                         Current_CTC__c, Expected_CTC__c, Email_ID__c, Location__c from Candidate__c];
        
        system.debug('The count of Candidates is : '+ lstcandidate.size());
        
        if(! lstcandidate.isEmpty())
        {
            for(Candidate__c temp : lstcandidate)
            {
                mapcandidates.put(temp.id, temp);
                system.debug('Record ID ' + temp.id);
                system.debug('Record Name : '+temp.name);
                system.debug('Record Candidate ID : '+temp.candidate_id__c);
                system.debug('Record Contact : '+temp.contact_number__c);
                system.debug('Current CTC : '+temp.current_CTC__c);
                system.debug('Expected CTC : '+temp.Expected_CTC__C);
                system.debug('Email : '+temp.Email_ID__c);
                system.debug('Location : '+temp.Location__c);
                system.debug('------------------------------------------------------------------------------');
            }
        } 
    }
    
    public void GetAllLeadRecords()
    {
        List<Lead> lstLeads=[select id, firstname, Lastname, Rating, ProductInterest__c, Status, Industry, Phone, Email from Lead];
        
        system.debug('The Lead collection size is : '+ lstleads.size());
        
        if(! lstleads.isempty())
        {
            for(Lead leadsList : lstleads)
            {
                system.debug('The Lead records are : '+ leadslist);
            }
        }
    }
    
    public void GetAllHiringManagers()
    {
    	List<Hiring_Manager__c> hm = [select id, name, Contact_Number__c, Email_ID__c, Location__c from Hiring_Manager__c];
        
        system.debug('The size of Hiring Manager collection is : '+ hm.size());
        
        if(! hm.isEmpty())
        {
           for(Hiring_Manager__c hmc : hm)
           {
               system.debug('The records in Hiring Manager object are : '+ hmc);
           }
        }
        
    } 
    
    public void GetAllPositionRecords()
    {
        List<Position__c> pos= [select id, Name, Candidates_Count__c, Close_Date__c, Open_Date__c, Location__c, 
                                Passport_Required_del__c, Travel_Required__c from Position__c];
    	
    	System.debug('The number of records in Position Obj : '+ pos.size());
        
        if(! pos.isempty())
        {
            for(Position__c temp : pos)
            {
                system.debug('The Position Details are : '+temp);
            }
        }
    
    }
    
    public void getAccountsByStartingchar(String startingchar)
    {
        if(startingchar !=null && startingchar !='')
        {
            startingchar+='%';
            List<Account> lstaccs=[Select Id,name,phone from account where name like : startingchar];
            
            if(! lstaccs.isEmpty())
            {
                for(Account acc : lstaccs)
                {
                    system.debug('Account record is : '+acc);
                }
            }
        }     
    }
    
    public void getContactsByAccountName(String accountName)
    {
        if(accountName != null && accountName!='')
        {
    		List<Account> lstacc=[select id, Name, Industry from Account where Name =: accountName];
        
       	 	Id lstAccId= lstacc.get(0).id;
        
        	List<Contact> lstCon=[Select id,Name,Phone,Email from Contact where Accountid =: lstAccId];
        
        	for(Contact con : lstCon)
       	 	{
            	system.debug(con);
        	}
    	}
    }
    
    public void getPositionByStatus(String status)
    {
        if(status!='' && status !=null)
        {
        	String PosQuery='select id, name,Location__c, position_status__c from Position__C where position_status__c =: status';
        	
            List<Position__c> lstpos=Database.query(PosQuery); 
                
            system.debug(lstPos.size());
            
            if(! lstPos.isEmpty())
            {
                for(Position__c pos : lstPos)
                {
                    system.debug(pos);
                }
            }
            
        }    
    }
	   
    public void getContactsAndOppFromAcc()
    {
        List<Account> lstAcc= [select id,name, 
                              (select id,phone from contacts),
                              (select id,name from opportunities) 
                              from account where name = 'Burlington Textiles Corp of America'];
    	
        system.debug(lstAcc);
        system.debug(lstAcc.size());
    }
 	
    
}