force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <customHelpPage>Calculator</customHelpPage>
    <description>Stores the data of the candidates for hiring</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Candidate_ID__c.field-meta.xml
<CustomField>
    <fullName>Candidate_ID__c</fullName>
    <description>It is a ID</description>
    <displayFormat>CID-{000000}</displayFormat>
    <label>Candidate ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Belagavi</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Position_Name__c.field-meta.xml
<CustomField>
    <fullName>Position_Name__c</fullName>
    <label>Position</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Position__c.Position_Status__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Please select the Position Name</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MessagingUtility.cls
public class MessagingUtility 
{
    /*public static void sendEmailToCandidate(Candidate__c cnd, String emailSubject)
    {
        if(cnd != null)
        {
            Messaging.SingleEmailMessage email=new Messaging.SingleEmailMessage();

            String[] setAddress= new String[]{cnd.Email_ID__c,'sns131094@gmail.com'};
            email.setToAddresses(setAddress);

            String[] ccaddress=new String[]{'sushantsaunkhe87@gmail.com'};
            email.setccaddresses(ccaddress);

            String[] bccaddress=new String[]{'shanu.akshata@gmail.com'};
            email.setbccaddresses(bccaddress);

            email.setreplyto('salunkhen203@gmail.com');

            email.SetSenderdisplayName('Accenture Recruitment Team');

            email.setsubject(emailSubject);
            
            String emailBody='Dear '+cnd.Name+', Thanks for showing interest in our organizations open positions.'+
            ' Your candidature has been submitted succesfully for the '+cnd.Position_Name__c+' position';
            
           // email.Setplaintextbody(emailBody);

            String htmlemailBody='Dear '+cnd.Name+',<br/><br/>'+
            'Thanks for showing interest in our organizations open positions.<br/><br/>'+
            'Your candidature has been submitted succesfully for the '+cnd.Position_Name__c+' position. Below are the details :<br/>'+
            '<br/>Candidate ID       :'+Cnd.Candidate_ID__c+
            '<br/>Candidate Name     :'+ Cnd.Name+
            '<br/>Phone              :'+cnd.Contact_Number__c+
            '<br/>Location           :'+cnd.Location__c+'<br/>'+
            '<br/><br/>Regards,<br/>'+
            'Talent Aquisition Team,<br/> Accenture Inc';
                        
            email.Sethtmlbody(htmlemailBody);

            Messaging.SendEmail(new Messaging.SingleEmailMessage[] {email});
        }

    }*/
    
    public static void sendEmailToMass()
    {
        Map<id,contact> mapContactsToSend=new Map<id,contact>([select id,firstname,lastname,email,PAN_Number__c 
                                                               from contact where email!= null and PAN_Number__c!= null]);
        if(! mapContactsToSend.isEmpty())
        {
            Messaging.MassEmailMessage massEmail=new Messaging.MassEmailMessage();
            Messaging.reserveSingleEmailCapacity(2);
            
            List<ID> contactIDs=new List<ID>();
            contactIDs.addall(mapContactsToSend.keyset());
            
            massEmail.setTargetObjectIds(contactIDs);
            
            EmailTemplate emailTemp=[select id,name from EmailTemplate where name='ApexMassEmail_Contact_UpdatePAN' limit 1];
            if(emailtemp!=null)
            {
                massEmail.setTemplateId(emailTemp.id);
                
                Messaging.sendEmail(new Messaging.MassEmailMessage[] {massEmail});
            }          
        }
    }
}